dist: bionic
sudo: true
notifications:
  email: false
language: c
cache:
  bundler: true
  ccache: true
git:
  depth: 1
  submodules: false
# branches:
#   only:
#   - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - GITHUB_USER=kuoruan
    - GITHUB_REPO=Build-Armbian
    - TERM=dumb

before_script:
  - df -h
  - free -mh
  - ccache -V
  - ccache -p
  - cd "$TRAVIS_BUILD_DIR" && touch .ignore_changes

script:
  - true
  - ccache -s

deploy:
  provider: releases
  file_glob: true
  file: "$HOME/imgs/*.xz"
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: m9UobKUTdl3NaPlnQvwpIomaZuyEd2bVUvZi4q07JOtsQEElXor+Ze+J8oI/Sj5ommxq6o/OsaWaB5q1HZWc7QJlZdHDRYVJ/b0e/qdN9k6cqNsbz/7U90B45Gf6TjX4RLbI59fuOxIldSp3BgX2aFAHpt/gcV9raFrBemPqs+qQMm+8vMvIx5sM5EaUgnveWrZLaOLXVwMKyeJh9Ro1i8pbCxhV3AAD1smODvsJEMVLs7LWUfQPDKbQ8hR+jwCcubAivL0y0tCqgq7Ic1Yscje6AH3hGpgBTme57NZIgiE2cwSs3xX9WHzMjio5P44aXyDnj3rmoH+uPl0GJ//Ui6tY6Q5mPN6WcJrciBQQDBJqFCRFp7ITXT1vE1rm8S3cYyGPwxdHaKNxRy0o58jlyDoPbGsfjjy/CkuTcY3rzJLUo5I1UnH784zm/+/Fue9HznZoKzNyeBtQycEAGP02roWblw+z0MaytGykN7pr7xLVgvRWofBNU2gMqHDRRg9HvDIo238RkSOS5iapz8Ormm21N8Up92ffRbyG77MPYMkyQXvV8WBiKNWD5UaHk3fz1W3VjRPMXEC3f/Q8/RDxCNqk3V39NmF4zmT/5me6TqqBAjdoavejdYYPeTjHv4M9tNIzB12hoYeCMPUx4hPMRr/DaGkLl6eyLmX5hUc5rrE=
